# Generated by Django 3.1.6 on 2021-02-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thoughts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoughtText', models.TextField(verbose_name='Thoughts')),
            ],
        ),
    ]
